BING_SEARCH_URL = "https://www.bing.com/search?q="

# Column names for presenting restaurant data
RESTAURANT_NAME = "Restaurant Name"
FOOD_TYPE = "Food Type"
LUNCH_PRICE = "Lunch Price (円)"
DINNER_PRICE = "Dinner Price (円)"
RATING = "Rating"
RESERVATION_LINK = "Reservation Link"
WALKING_TIME = "Walking Time"
AVAILABILITY = "Availability"
IKYU_ID = "Ikyu ID"
EARLIEST_TARGET_RESERVATION_DATE = "2023-12-3"
LATEST_TARGET_RESERVATION_DATE = "2023-12-9"
RESERVATION_STATUS = "Reservation Status"
LUNCH = "lunch"
DINNER = "dinner"
